### ISSUE TITLE
When 2nd monitor is connected doesn't activate full screen

### ISSUE THREAD

**Issue by j-ales** [aleslab/psychtoolboxProjects#1]
Work around: explicitly enable full screen mode in the paradigm file.

**Comment by abigailrilee** [comment]
Right now the work around means that full screen is always enabled even when there is only one screen. I haven't yet been able to revert this.

**Comment by j-ales** [comment]
That is working as intended.  Enabling full screen forces a full screen no matter the monitor setup.
