### ISSUE TITLE
Add specification of different randomization types in paradigm files

### ISSUE THREAD

**Issue by j-ales** [aleslab/psychtoolboxProjects#10]
We should add a way to specify the type of randomization needed for a paradigm:
e.g.:

(implemented) Fully random: Just take all conditions and display them in a random order
Block Design: Present the same condition repeatedly, then switch conditions
Custom: Let the user explicitly set the trial orders.

**Comment by fa28** [comment]
I was thinking in block perhaps like this?


1. 0.04

2. 0.08

3. 0.15

Break 5 mins

4. 0.08

5. 0.15

6. 0.04

Break 5 mins

7. 0.15

8. 0.08

9.  0.04


I will have to try it a few times to see what it's like put it seems a sensible way to do it what do you think?


have been in lab this morn and everything is running fine. Only a minor issue in that the Matlab icon doesn't work but i just opened in from the command line.







________________________________

**Comment by j-ales** [comment]
commit 1e82c63f adds in block design.  Setting expInfo.randomizationType to 'blocked'

**Comment by j-ales** [comment]
v0.32.0
Block design has been extended to blocking groups of conditions.
Custom has been implmented.
